# Generated by Django 5.1.5 on 2025-02-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='create_post',
            field=models.TextField(default='Write your post here...'),
        ),
    ]
